FROM node:18-alpine

RUN apk add --no-cache python3 make g++

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install --omit=dev

COPY libs ./libs

RUN npx prisma generate

CMD ["npx", "prisma", "push", "--accept-data-loss"]
