export const MICROSERVICE_LIST = {
  AUTH_SERVICE: 'AUTH_SERVICE',
  KAFKA_SERVICE: 'KAFKA_SERVICE',
  USER_SERVICE: 'USER_SERVICE',
  INVENTORY_SERVICE: 'INVENTORY_SERVICE',
  CATALOG_SERVICE: 'CATALOG_SERVICE',
  MARKET_SERVICE: 'MARKET_SERVICE',
};
